version: "3.8"
services:
  utility:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - /project/workspace/csv-downloader:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_user_password
    volumes:
      - data:/app/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  data:
