version: "3.8"
services:
  utility:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - /project/sandbox/csv-downloader:/app
    ports:
      - 3000:3000
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_user_password
    ports:
      - "3306:3306"
    volumes:
      - my-mysql-data:/var/lib/mysql

volumes:
  my-mysql-data:
