# Use the latest long-term support version of Node.js
FROM node:lts-slim

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Install nodemon globally
RUN npm install -g nodemon

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port that the app runs on (optional)
EXPOSE 3000

# Set environment variable
ENV NODE_ENV production

# Use nodemon to start the app
CMD ["nodemon", "app.js"]
